version: '3.8'

services:
  # PHP-FPM service
  app:
    image: php:8.2-fpm
    container_name: laravel-absensi
    volumes:
      - ./absensi:/var/www/html/absensi
    working_dir: /var/www/html/absensi
    networks:
      - laravel

  # Nginx web server
  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  # Composer (PHP dependency management)
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./absensi:/var/www/html/absensi
    working_dir: /var/www/html/absensi
    command: ["composer", "create-project", "laravel/laravel", "."]
   # command: ["composer", "install"]
    #command: ["sh", "-c", "composer install && tail -f /dev/null"]

    networks:
      - laravel

  # Node.js (for Vite, npm run dev, dll)
  node:
    image: node:24.2.0-alpine
    container_name: node
    environment:
      - NODE_ENV=development
    volumes:
      - ./absensi:/var/www/html/absensi
    working_dir: /var/www/html/absensi
    ports: 
      - "8001:8001"  # optional: kalau kamu perlu expose port (misal vite dev server)
    command: sh -c "npm install && npm run dev" # sesuaikan jika kamu pakai 'npm run build' di production
    networks:
      - laravel

  # MySQL database
  mysql:
    image: mysql:8.0  # ganti dari 9.3.0 ke versi stable
    container_name: mysql_laravel
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3308:3306"  # optional: agar bisa diakses dari host
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
